### ISSUE TITLE
Title is not visible

### ISSUE THREAD

**Issue by stealthcopter** [lozzd/octopus-energy-rates-card#10]
Thanks for this card. One small issue is that the title doesn't appear to be working for me.

```yaml
type: custom:octopus-energy-rates-card
title: Agile Export Rates
entity: sensor.octopus_energy_electricity_21l4374621_2200043442484_export_current_rate
cols: 2
showday: true
showpast: true
exportrates: true
```

![Screenshot from 2023-04-04 13-32-49](https://user-images.githubusercontent.com/1211162/229792472-2c33193b-9e13-4a02-ab07-593ccdeae054.png)

Doesn't seem like anything I can do can make it appear. Maybe there's something wrong with my setup elsewhere, but I'm not using any themes or anything.

Version: 0.1.3
HA Version: 2023.3.6
