### ISSUE TITLE
Feature request: support for IO Dispatching binary sensor

### ISSUE THREAD

**Issue by ragg987** [lozzd/octopus-energy-rates-card#81]
Hi, thanks for this great card, it really helps me to visualise rates and specified loads via target sensors. Would you be able to add support for the Dispatching sensor in Intelligent Octopus? I tried adding it to the card config but it gets ignored - I assume as the attributes of this sensor are not quite the same as a target sensor? Here is what the attributes of the sensor look like.

```
**binary_sensor.octopus_energy_a_XXXXX_intelligent_dispatching**

planned_dispatches: 
- start: '2024-07-22T22:30:00+01:00'
  end: '2024-07-22T23:00:00+01:00'
  charge_in_kwh: -1.73
  source: smart-charge
  location: null
- start: '2024-07-22T23:00:00+01:00'
  end: '2024-07-23T06:00:00+01:00'
  charge_in_kwh: -38.62
  source: smart-charge
  location: null

completed_dispatches: 
- start: '2024-07-20T02:30:00+01:00'
  end: '2024-07-20T03:00:00+01:00'
  charge_in_kwh: -1.59
  source: null
  location: AT_HOME
- start: '2024-07-20T04:30:00+01:00'
  end: '2024-07-20T05:00:00+01:00'
  charge_in_kwh: -1.1
  source: null
  location: AT_HOME
- start: '2024-07-20T04:00:00+01:00'
  end: '2024-07-20T04:30:00+01:00'
  charge_in_kwh: -0.07
  source: null
  location: AT_HOME
- start: '2024-07-20T03:30:00+01:00'
  end: '2024-07-20T04:00:00+01:00'
  charge_in_kwh: -1.83
  source: null
  location: AT_HOME
- start: '2024-07-20T05:00:00+01:00'
  end: '2024-07-20T05:30:00+01:00'
  charge_in_kwh: -0.46
  source: null
  location: AT_HOME
- start: '2024-07-20T14:00:00+01:00'
  end: '2024-07-20T14:30:00+01:00'
  charge_in_kwh: -0.01
  source: null
  location: AT_HOME
- start: '2024-07-20T16:00:00+01:00'
  end: '2024-07-20T16:30:00+01:00'
  charge_in_kwh: -0.5
  source: null
  location: AT_HOME
- start: '2024-07-20T15:30:00+01:00'
  end: '2024-07-20T16:00:00+01:00'
  charge_in_kwh: -0.59
  source: null
  location: AT_HOME
- start: '2024-07-21T00:00:00+01:00'
  end: '2024-07-21T00:30:00+01:00'
  charge_in_kwh: -1.87
  source: null
  location: AT_HOME
- start: '2024-07-20T23:30:00+01:00'
  end: '2024-07-21T00:00:00+01:00'
  charge_in_kwh: -1.6
  source: null
  location: AT_HOME
- start: '2024-07-21T00:30:00+01:00'
  end: '2024-07-21T01:00:00+01:00'
  charge_in_kwh: -0.77
  source: null
  location: AT_HOME
- start: '2024-07-21T15:30:00+01:00'
  end: '2024-07-21T16:00:00+01:00'
  charge_in_kwh: -0.01
  source: null
  location: AT_HOME
- start: '2024-07-21T23:00:00+01:00'
  end: '2024-07-21T23:30:00+01:00'
  charge_in_kwh: -1.01
  source: null
  location: AT_HOME
- start: '2024-07-22T00:00:00+01:00'
  end: '2024-07-22T00:30:00+01:00'
  charge_in_kwh: -1.83
  source: null
  location: AT_HOME
- start: '2024-07-22T01:00:00+01:00'
  end: '2024-07-22T01:30:00+01:00'
  charge_in_kwh: -0.69
  source: null
  location: AT_HOME
- start: '2024-07-22T00:30:00+01:00'
  end: '2024-07-22T01:00:00+01:00'
  charge_in_kwh: -1.87
  source: null
  location: AT_HOME
- start: '2024-07-22T18:00:00+01:00'
  end: '2024-07-22T18:30:00+01:00'
  charge_in_kwh: -0.01
  source: null
  location: AT_HOME

data_last_retrieved: 2024-07-22T19:19:20.869528+01:00
last_evaluated: 2024-07-22T19:22:20.869712+01:00
provider: MYENERGI
vehicle_battery_size_in_kwh: 80.7
charge_point_power_in_kw: 7.4
current_start: null
current_end: null
next_start: 2024-07-22T22:30:00+01:00
next_end: 2024-07-23T06:00:00+01:00
icon: mdi:power-plug-battery
friendly_name: Intelligent Dispatching (A-XXXXX)
```
