### ISSUE TITLE
Feature Request - agile predictions

### ISSUE THREAD

**Issue by tomkerswill** [lozzd/octopus-energy-rates-card#88]
Would you consider adding the ability to include Octopus Agile predictions? It would be especially useful to have predicted rates for a day or two in the future.

This data is already easy to get into Home Assistant, so I think it would just be a case of adding another config item to set the sensor.

**Comment by elyobelyob** [comment]
FYI, the OE Greenness Forecast only gives a forecast for 23:00 to 06:00 each day.

**Comment by tomkerswill** [comment]
The Agile Predict site, here, has a nice API, and it's easy to get that into HA:

https://prices.fly.dev/

This seems to stretch for a week - and is not official, but seems to be a good guide to what the prices could be.

**Comment by elyobelyob** [comment]
You could try this ... https://github.com/elyobelyob/octopus-energy-greenness-forecast-card ...

I didn't want to mention it myself, but it's what I use ...

**Comment by pcb1962** [comment]
or this:
![image](https://github.com/user-attachments/assets/0164c105-17b7-40f4-bb3e-a5ac8f61fe4f)
```yaml
type: custom:apexcharts-card
experimental:
  color_threshold: true
header:
  show: true
  title: Greenness Forecast
graph_span: 7d
span:
  start: hour
apex_config:
  chart:
    height: 135
  stroke:
    width: 4
  xaxis:
    labels:
      format: ddd
series:
  - entity: sensor.octopus_energy_a_xxxxxxxx_greenness_forecast_current_index
    name: Forecast
    show:
      in_header: false
      legend_value: false
    color_threshold:
      - value: 0
        color: red
      - value: 40
        color: orange
      - value: 80
        color: green
    data_generator: |
      return entity.attributes.forecast.slice(0, 7).map((entry) => {
      return [new Date(entry.start), entry.greenness_score];
        });type: ''
```
Not sure where I got this from so can't give credit unfortunately.
